// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DBInstanceSpec defines the desired state of DBInstance.
//
// Detailed information about an instance.
type DBInstanceSpec struct {

	// This parameter does not apply to Amazon DocumentDB. Amazon DocumentDB does
	// not perform minor version upgrades regardless of the value set.
	//
	// Default: false
	AutoMinorVersionUpgrade *bool `json:"autoMinorVersionUpgrade,omitempty"`
	// The Amazon EC2 Availability Zone that the instance is created in.
	//
	// Default: A random, system-chosen Availability Zone in the endpoint's Amazon
	// Web Services Region.
	//
	// Example: us-east-1d
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	AvailabilityZone *string `json:"availabilityZone,omitempty"`
	// The CA certificate identifier to use for the DB instance's server certificate.
	//
	// For more information, see Updating Your Amazon DocumentDB TLS Certificates
	// (https://docs.aws.amazon.com/documentdb/latest/developerguide/ca_cert_rotation.html)
	// and Encrypting Data in Transit (https://docs.aws.amazon.com/documentdb/latest/developerguide/security.encryption.ssl.html)
	// in the Amazon DocumentDB Developer Guide.
	CACertificateIdentifier *string `json:"caCertificateIdentifier,omitempty"`
	// A value that indicates whether to copy tags from the DB instance to snapshots
	// of the DB instance. By default, tags are not copied.
	CopyTagsToSnapshot *bool `json:"copyTagsToSnapshot,omitempty"`
	// The identifier of the cluster that the instance will belong to.
	// +kubebuilder:validation:Required
	DBClusterIdentifier *string `json:"dbClusterIdentifier"`
	// The compute and memory capacity of the instance; for example, db.r5.large.
	// +kubebuilder:validation:Required
	DBInstanceClass *string `json:"dbInstanceClass"`
	// The instance identifier. This parameter is stored as a lowercase string.
	//
	// Constraints:
	//
	//   - Must contain from 1 to 63 letters, numbers, or hyphens.
	//
	//   - The first character must be a letter.
	//
	//   - Cannot end with a hyphen or contain two consecutive hyphens.
	//
	// Example: mydbinstance
	// +kubebuilder:validation:Required
	DBInstanceIdentifier *string `json:"dbInstanceIdentifier"`
	// The name of the database engine to be used for this instance.
	//
	// Valid value: docdb
	// +kubebuilder:validation:Required
	Engine *string `json:"engine"`
	// A value that indicates whether to enable Performance Insights for the DB
	// Instance. For more information, see Using Amazon Performance Insights (https://docs.aws.amazon.com/documentdb/latest/developerguide/performance-insights.html).
	PerformanceInsightsEnabled *bool `json:"performanceInsightsEnabled,omitempty"`
	// The KMS key identifier for encryption of Performance Insights data.
	//
	// The KMS key identifier is the key ARN, key ID, alias ARN, or alias name for
	// the KMS key.
	//
	// If you do not specify a value for PerformanceInsightsKMSKeyId, then Amazon
	// DocumentDB uses your default KMS key. There is a default KMS key for your
	// Amazon Web Services account. Your Amazon Web Services account has a different
	// default KMS key for each Amazon Web Services region.
	PerformanceInsightsKMSKeyID  *string                                  `json:"performanceInsightsKMSKeyID,omitempty"`
	PerformanceInsightsKMSKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"performanceInsightsKMSKeyRef,omitempty"`
	// The time range each week during which system maintenance can occur, in Universal
	// Coordinated Time (UTC).
	//
	// Format: ddd:hh24:mi-ddd:hh24:mi
	//
	// The default is a 30-minute window selected at random from an 8-hour block
	// of time for each Amazon Web Services Region, occurring on a random day of
	// the week.
	//
	// Valid days: Mon, Tue, Wed, Thu, Fri, Sat, Sun
	//
	// Constraints: Minimum 30-minute window.
	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty"`
	// A value that specifies the order in which an Amazon DocumentDB replica is
	// promoted to the primary instance after a failure of the existing primary
	// instance.
	//
	// Default: 1
	//
	// Valid values: 0-15
	PromotionTier *int64 `json:"promotionTier,omitempty"`
	// The tags to be assigned to the instance. You can assign up to 10 tags to
	// an instance.
	Tags []*Tag `json:"tags,omitempty"`
}

// DBInstanceStatus defines the observed state of DBInstance
type DBInstanceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Specifies the number of days for which automatic snapshots are retained.
	// +kubebuilder:validation:Optional
	BackupRetentionPeriod *int64 `json:"backupRetentionPeriod,omitempty"`
	// The details of the DB instance's server certificate.
	// +kubebuilder:validation:Optional
	CertificateDetails *CertificateDetails `json:"certificateDetails,omitempty"`
	// Specifies the current state of this database.
	// +kubebuilder:validation:Optional
	DBInstanceStatus *string `json:"dbInstanceStatus,omitempty"`
	// Specifies information on the subnet group that is associated with the instance,
	// including the name, description, and subnets in the subnet group.
	// +kubebuilder:validation:Optional
	DBSubnetGroup *DBSubnetGroup_SDK `json:"dbSubnetGroup,omitempty"`
	// The Amazon Web Services Region-unique, immutable identifier for the instance.
	// This identifier is found in CloudTrail log entries whenever the KMS key for
	// the instance is accessed.
	// +kubebuilder:validation:Optional
	DBIResourceID *string `json:"dbiResourceID,omitempty"`
	// A list of log types that this instance is configured to export to CloudWatch
	// Logs.
	// +kubebuilder:validation:Optional
	EnabledCloudwatchLogsExports []*string `json:"enabledCloudwatchLogsExports,omitempty"`
	// Specifies the connection endpoint.
	// +kubebuilder:validation:Optional
	Endpoint *Endpoint `json:"endpoint,omitempty"`
	// Indicates the database engine version.
	// +kubebuilder:validation:Optional
	EngineVersion *string `json:"engineVersion,omitempty"`
	// Provides the date and time that the instance was created.
	// +kubebuilder:validation:Optional
	InstanceCreateTime *metav1.Time `json:"instanceCreateTime,omitempty"`
	// If StorageEncrypted is true, the KMS key identifier for the encrypted instance.
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyID,omitempty"`
	// Specifies the latest time to which a database can be restored with point-in-time
	// restore.
	// +kubebuilder:validation:Optional
	LatestRestorableTime *metav1.Time `json:"latestRestorableTime,omitempty"`
	// Specifies that changes to the instance are pending. This element is included
	// only when changes are pending. Specific changes are identified by subelements.
	// +kubebuilder:validation:Optional
	PendingModifiedValues *PendingModifiedValues `json:"pendingModifiedValues,omitempty"`
	// Specifies the daily time range during which automated backups are created
	// if automated backups are enabled, as determined by the BackupRetentionPeriod.
	// +kubebuilder:validation:Optional
	PreferredBackupWindow *string `json:"preferredBackupWindow,omitempty"`
	// Not supported. Amazon DocumentDB does not currently support public endpoints.
	// The value of PubliclyAccessible is always false.
	// +kubebuilder:validation:Optional
	PubliclyAccessible *bool `json:"publiclyAccessible,omitempty"`
	// The status of a read replica. If the instance is not a read replica, this
	// is blank.
	// +kubebuilder:validation:Optional
	StatusInfos []*DBInstanceStatusInfo `json:"statusInfos,omitempty"`
	// Specifies whether or not the instance is encrypted.
	// +kubebuilder:validation:Optional
	StorageEncrypted *bool `json:"storageEncrypted,omitempty"`
	// Provides a list of VPC security group elements that the instance belongs
	// to.
	// +kubebuilder:validation:Optional
	VPCSecurityGroups []*VPCSecurityGroupMembership `json:"vpcSecurityGroups,omitempty"`
}

// DBInstance is the Schema for the DBInstances API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.dbInstanceStatus`
type DBInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DBInstanceSpec   `json:"spec,omitempty"`
	Status            DBInstanceStatus `json:"status,omitempty"`
}

// DBInstanceList contains a list of DBInstance
// +kubebuilder:object:root=true
type DBInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBInstance `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DBInstance{}, &DBInstanceList{})
}
